# Generated by Django 4.2.2 on 2023-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcustom",
            name="slug",
        ),
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=models.CharField(
                help_text="Example (001100)",
                max_length=6,
                unique=True,
                verbose_name="Hex Code",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="title_fa",
            field=models.CharField(max_length=32, unique=True, verbose_name="Title Fa"),
        ),
    ]
