# Generated by Django 4.2 on 2023-04-28 14:46

import ckeditor.fields
from django import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
