# Generated by Django 4.2.2 on 2023-06-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_productcustom_slug_alter_color_hex_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcustom",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, null=True, verbose_name="Slug"
            ),
        ),
    ]
