# Generated by Django 4.2.2 on 2023-06-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_productcustom_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="selling_counts",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Selling counts"
            ),
        ),
    ]
