# Generated by Django 4.2.2 on 2023-06-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_selling_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="selling_counts",
            field=models.PositiveIntegerField(
                default=0, editable=False, null=True, verbose_name="Selling counts"
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=64, verbose_name="Category Title"),
                ),
                ("slug", models.SlugField(allow_unicode=True, verbose_name="Slug")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, to="product.category", verbose_name="Categories"
            ),
        ),
    ]
