# Generated by Django 4.2 on 2023-04-30 16:21

from django import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_productcustom_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcustom",
            old_name="counts",
            new_name="quantity",
        ),
        migrations.AlterField(
            model_name="productcustom",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                editable=False,
                max_length=64,
                verbose_name="Slug",
            ),
        ),
    ]
