# Generated by Django 4.2.2 on 2023-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_selling_counts_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_root",
            field=models.BooleanField(default=False, verbose_name="Root category"),
        ),
    ]
