# Generated by Django 4.2.2 on 2023-06-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_category_is_root"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_root",
        ),
        migrations.AddField(
            model_name="category",
            name="is_first",
            field=models.BooleanField(default=False, verbose_name="First category"),
        ),
    ]
