# Generated by Django 4.2.2 on 2023-06-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_remove_category_is_root_category_is_first"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_first",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="First category"
            ),
        ),
    ]
