# Generated by Django 4.2.2 on 2023-06-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_category_is_first"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="title_en",
            field=models.CharField(max_length=64, null=True, verbose_name="Title En"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="product.category",
                verbose_name="Parent Category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=64, verbose_name="Title Fa"),
        ),
    ]
