# Generated by Django 4.2.2 on 2023-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_category_title_en_alter_category_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=64, verbose_name="Slug"
            ),
        ),
    ]
