# Generated by Django 4.2 on 2023-05-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_options_alter_cartitem_options_cart_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Total price"
            ),
        ),
    ]
