# Generated by Django 4.2 on 2023-05-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_cart_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.IntegerField(default=0, verbose_name="Total price"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="total_price",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Total price"
            ),
        ),
    ]
