# Generated by Django 4.2 on 2023-05-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_cart_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="idkc",
            field=models.BigIntegerField(
                editable=False, null=True, verbose_name="idkc"
            ),
        ),
    ]
