# Generated by Django 4.2 on 2023-05-17 10:06

from django import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_cartitem_idkc_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="base_total_price",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Base total price"
            ),
        ),
    ]
