# Generated by Django 4.2 on 2023-05-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_productcustom_quantity"),
        ("cart", "0007_cartitem_base_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cart_item",
                to="product.productcustom",
                verbose_name="Product",
            ),
        ),
    ]
