# Generated by Django 4.2 on 2023-05-21 14:41

from django import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_alter_cartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.IntegerField(default=0, verbose_name="Total price"),
        ),
    ]
