# Generated by Django 4.2.2 on 2023-06-20 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oid",
                    models.PositiveBigIntegerField(default=1000, verbose_name="OID"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Quantity"),
                ),
                (
                    "payable_price",
                    models.IntegerField(default=0, verbose_name="Payable price"),
                ),
                (
                    "discount_price",
                    models.IntegerField(default=0, verbose_name="Discount price"),
                ),
                (
                    "address_info",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Address info",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("N", "Normal"), ("Q", "Quick")],
                        default=("N", "Normal"),
                        max_length=32,
                        verbose_name="Delivery type",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("BA", "Bank"), ("DD", "Didipay")],
                        default=("N", "Normal"),
                        max_length=32,
                        verbose_name="Payment method",
                    ),
                ),
                (
                    "bank_tracking_code",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Bank tracking code",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unsuccessful", "Unsuccessful"),
                            ("successful", "Successful"),
                            ("pending", "Pending"),
                            ("dispatching", "Dispatching"),
                            ("dispatched", "Dispatched"),
                        ],
                        default="unsuccessful",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is paid")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="order",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantity purchased"
                    ),
                ),
                (
                    "total_price",
                    models.IntegerField(default=0, verbose_name="Total price"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="order.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="order_item",
                        to="product.productcustom",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
            },
        ),
    ]
