# Generated by Django 4.2 on 2023-05-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_success",
            new_name="is_paid",
        ),
        migrations.AddField(
            model_name="order",
            name="address_info",
            field=models.TextField(
                default="", max_length=256, verbose_name="Address info"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unsuccessful", "Unsuccessful"),
                    ("successful", "Successful"),
                    ("pending", "Pending"),
                    ("dispatching", "Dispatching"),
                    ("dispatched", "Dispatched"),
                ],
                default=("unsuccessful", "Unsuccessful"),
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantity purchased"
            ),
        ),
    ]
