# Generated by Django 4.2.2 on 2023-06-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Purchased Quantity"
            ),
        ),
    ]
