# Generated by Django 4.2 on 2023-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_success",
        ),
        migrations.AddField(
            model_name="order",
            name="address_info",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="Address info"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="bank_tracking_code",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Bank tracking code"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("N", "Normal"), ("Q", "Quick")],
                default=("N", "Normal"),
                max_length=32,
                verbose_name="Delivery type",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Is paid"),
        ),
        migrations.AddField(
            model_name="order",
            name="oid",
            field=models.PositiveBigIntegerField(default=1000, verbose_name="OID"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("BA", "Bank"), ("DD", "Didipay")],
                default=("N", "Normal"),
                max_length=32,
                verbose_name="Payment method",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unsuccessful", "Unsuccessful"),
                    ("successful", "Successful"),
                    ("pending", "Pending"),
                    ("dispatching", "Dispatching"),
                    ("dispatched", "Dispatched"),
                ],
                default=("unsuccessful", "Unsuccessful"),
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantity purchased"
            ),
        ),
    ]
