# Generated by Django 4.2 on 2023-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_remove_order_is_success_order_address_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unsuccessful", "Unsuccessful"),
                    ("successful", "Successful"),
                    ("pending", "Pending"),
                    ("dispatching", "Dispatching"),
                    ("dispatched", "Dispatched"),
                ],
                default="unsuccessful",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
