# Generated by Django 4.2 on 2023-04-23 11:33

import apps.account.validators
from django import settings
from django import migrations, models
import django
import django_jalali.db.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="Mobile number"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("seller", "Seller"),
                            ("manager", "Manager"),
                            ("creator", "Creator"),
                        ],
                        default=("user", "User"),
                        max_length=32,
                        verbose_name="Access level",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_admin", models.BooleanField(default=False, verbose_name="Admin")),
                (
                    "verified",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Verified"
                    ),
                ),
            ],
            options={
                "verbose_name": "User account",
                "verbose_name_plural": "Users accounts",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="First name"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Male"), ("f", "Female")],
                        max_length=8,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "melli_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[apps.account.validators.arithmetic_numbers],
                        verbose_name="Melli code",
                    ),
                ),
                (
                    "is_foreign_citizen",
                    models.BooleanField(
                        default=False, verbose_name="I'm foreign citizen"
                    ),
                ),
                (
                    "is_subscriber",
                    models.BooleanField(default=False, verbose_name="Subscribe"),
                ),
                (
                    "date_of_birth",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image/profiles",
                        verbose_name="Profile image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated time"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "Users profiles",
            },
        ),
    ]
