# Generated by Django 4.2 on 2023-04-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="Mobile Number"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_admin", models.BooleanField(default=False, verbose_name="Admin")),
            ],
            options={
                "verbose_name": "User account",
                "verbose_name_plural": "User accounts",
            },
        ),
    ]
