# Generated by Django 4.2 on 2023-04-23 11:45

from django import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("manager", "Manager"),
                    ("seller", "Seller"),
                    ("creator", "Creator"),
                ],
                default=("user", "User"),
                max_length=32,
                verbose_name="Access level",
            ),
        ),
    ]
