# Generated by Django 4.2 on 2023-04-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "User account",
                "verbose_name_plural": "Users accounts",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("seller", "Seller"),
                    ("manager", "Manager"),
                    ("creator", "Creator"),
                ],
                default=("user", "User"),
                max_length=32,
                verbose_name="Access level",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="Mobile number"
            ),
        ),
    ]
