# Generated by Django 4.2.2 on 2023-06-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("manager", "Manager"),
                    ("seller", "Seller"),
                    ("creator", "Creator"),
                ],
                default="user",
                max_length=32,
                verbose_name="Access level",
            ),
        ),
    ]
