# Generated by Django 4.2 on 2023-05-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_access_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="First name"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Last name"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        default=None, max_length=32, verbose_name="Province"
                    ),
                ),
                (
                    "city",
                    models.CharField(default=None, max_length=32, verbose_name="City"),
                ),
                ("address", models.TextField(max_length=256, verbose_name="Address")),
                (
                    "post_code",
                    models.CharField(max_length=10, verbose_name="Postal_code"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
