# Generated by Django 4.2 on 2023-04-21 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_options_user_access_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="First name"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Male"), ("f", "Female")],
                        max_length=8,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "melli_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Melli code"
                    ),
                ),
                (
                    "date_of_birth",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "is_foreign_citizen",
                    models.BooleanField(
                        default=False, verbose_name="I'm foreign citizen"
                    ),
                ),
                (
                    "is_subscriber",
                    models.BooleanField(default=False, verbose_name="Subscribe"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image/profiles",
                        verbose_name="Profile image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated time"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "Users profiles",
            },
        ),
    ]
