# Generated by Django 4.2 on 2023-06-18 13:17

from django import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_access_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=128, verbose_name="Token")),
                ("mobile", models.CharField(max_length=11, verbose_name="Mobile")),
                (
                    "otp",
                    models.CharField(max_length=5, verbose_name="One time password"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create time"),
                ),
            ],
            options={
                "verbose_name": "Login otp",
                "verbose_name_plural": "Login otps",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("is_manager", "Is_manager"),
                    ("is_seller", "Is_seller"),
                    ("is_creator", "Is_creator"),
                ],
                "verbose_name": "User account",
                "verbose_name_plural": "Users accounts",
            },
        ),
    ]
