# Generated by Django 4.2 on 2023-04-22 19:04

import apps.account.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="melli_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[apps.account.validators.arithmetic_numbers],
                verbose_name="Melli code",
            ),
        ),
    ]
