# Generated by Django 4.2 on 2023-05-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "verbose_name": "User address",
                "verbose_name_plural": "User addresses",
            },
        ),
        migrations.AddField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Create time"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Update time"
            ),
        ),
    ]
