# Generated by Django 4.2 on 2023-06-18 13:23

from django import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_otp_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={
                "verbose_name": "One time password",
                "verbose_name_plural": "One time passwords",
            },
        ),
        migrations.AlterField(
            model_name="otp",
            name="otp",
            field=models.CharField(
                max_length=5, null=True, verbose_name="One time password"
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="token",
            field=models.CharField(max_length=128, null=True, verbose_name="Token"),
        ),
    ]
