# Generated by Django 4.2 on 2023-06-18 13:26

from django import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_otp_options_alter_otp_otp_alter_otp_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="mobile",
            field=models.CharField(max_length=11, unique=True, verbose_name="Mobile"),
        ),
    ]
