# Generated by Django 4.2 on 2023-05-18 12:21

import apps.account.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_address_options_address_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=0,
                        max_length=2,
                        validators=[apps.account.validators.arithmetic_numbers],
                        verbose_name="Code",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Title")),
            ],
        ),
        migrations.AlterField(
            model_name="address",
            name="post_code",
            field=models.CharField(
                max_length=10,
                validators=[apps.account.validators.arithmetic_numbers],
                verbose_name="Postal_code",
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Title")),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.province",
                        verbose_name="Province",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.province",
                verbose_name="Province",
            ),
        ),
    ]
