# Generated by Django 4.2 on 2023-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_province_alter_address_post_code_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="title",
        ),
        migrations.RemoveField(
            model_name="province",
            name="title",
        ),
        migrations.AddField(
            model_name="city",
            name="title_en",
            field=models.CharField(default="", max_length=32, verbose_name="Title en"),
        ),
        migrations.AddField(
            model_name="city",
            name="title_fa",
            field=models.CharField(default="", max_length=32, verbose_name="Title fa"),
        ),
        migrations.AddField(
            model_name="province",
            name="title_en",
            field=models.CharField(default="", max_length=32, verbose_name="Title en"),
        ),
        migrations.AddField(
            model_name="province",
            name="title_fa",
            field=models.CharField(default="", max_length=32, verbose_name="Title fa"),
        ),
    ]
