# Generated by Django 4.2 on 2023-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_remove_city_title_remove_province_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="province",
            name="abbreviation",
            field=models.CharField(
                default="None", max_length=2, verbose_name="abbreviation"
            ),
        ),
    ]
