# Generated by Django 4.2 on 2023-05-18 12:58

import apps.account.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_province_abbreviation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="title_fa",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="province",
            old_name="title_fa",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="city",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="province",
            name="abbreviation",
        ),
        migrations.RemoveField(
            model_name="province",
            name="code",
        ),
        migrations.RemoveField(
            model_name="province",
            name="title_en",
        ),
        migrations.AddField(
            model_name="city",
            name="slug",
            field=models.SlugField(default="None", max_length=32, verbose_name="Slug"),
        ),
        migrations.AddField(
            model_name="province",
            name="slug",
            field=models.SlugField(default="None", max_length=32, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="province",
            name="id",
            field=models.CharField(
                max_length=2,
                primary_key=True,
                serialize=False,
                validators=[apps.account.validators.arithmetic_numbers],
                verbose_name="ID",
            ),
        ),
    ]
