# Generated by Django 4.2 on 2023-05-18 17:45

import apps.address.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        validators=[apps.address.validators.arithmetic_numbers],
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="None", max_length=32, verbose_name="Slug"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=32, verbose_name="Title fa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="None", max_length=32, verbose_name="Slug"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=32, verbose_name="Title fa"
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.province",
                        verbose_name="Province",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        default="", max_length=32, verbose_name="First name"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        default="", max_length=32, verbose_name="Last name"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        default="09000000000",
                        max_length=11,
                        verbose_name="Mobile number",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        default="None", max_length=32, verbose_name="Province"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="None", max_length=32, verbose_name="City"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        max_length=256, unique=True, verbose_name="Address"
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[apps.address.validators.arithmetic_numbers],
                        verbose_name="Postal_code",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Create time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update time"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User address",
                "verbose_name_plural": "User addresses",
            },
        ),
    ]
