# Generated by Django 4.2 on 2023-05-18 23:46

import apps.address.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="address",
            name="lastname",
        ),
        migrations.AddField(
            model_name="address",
            name="fullname",
            field=models.CharField(default="", max_length=32, verbose_name="Full name"),
        ),
        migrations.AlterField(
            model_name="address",
            name="mobile",
            field=models.CharField(max_length=11, verbose_name="Mobile number"),
        ),
        migrations.AlterField(
            model_name="city",
            name="id",
            field=models.CharField(
                max_length=2,
                primary_key=True,
                serialize=False,
                validators=[apps.address.validators.arithmetic_numbers],
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default="None", max_length=32, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default="None", max_length=32, verbose_name="Slug"
            ),
        ),
    ]
