# Generated by Django 4.2 on 2023-05-19 11:11

from django import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_alter_address_city_alter_address_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="id",
            field=models.BigIntegerField(
                editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(default="", max_length=32, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default="None", max_length=64, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="id",
            field=models.BigIntegerField(
                editable=False, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(default="", max_length=32, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="province",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default="None", max_length=64, verbose_name="Slug"
            ),
        ),
    ]
