# Generated by Django 4.2 on 2023-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0004_alter_city_id_alter_city_name_alter_city_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.TextField(max_length=256, verbose_name="Address"),
        ),
    ]
